# Generated by Django 4.2.3 on 2024-02-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_alter_expense_currency_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friends',
            old_name='members',
            new_name='friends',
        ),
    ]
