# Generated by Django 4.2.3 on 2024-02-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_members_friends_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
