# Generated by Django 4.2.3 on 2024-02-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_expense_remaining_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='owing',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
